SGFinansAS/elm-components

- src/Nordea/Components/Button.elm
- src/Nordea/Resources/Colors.elm
> Update button to use new design

- explorer/src/Stories/RadioButton.elm
- src/Nordea/Components/RadioButton.elm
> Fix radio button styling and improve story

- explorer/src/Explorer.elm
- explorer/src/Stories/Spinner.elm
- src/Nordea/Components/Spinner.elm
- src/Nordea/Resources/Icons.elm
Added the spinner used in Partnerhub.
Usage:
```
Spinner.default[attributes]
Spinner.small[attributes]
```
https://user-images.githubusercontent.com/14363025/134309858-00f6bd74-23e9-437a-bd70-5637c9100292.mov
> Add spinner

- explorer/src/Config.elm
- explorer/src/Explorer.elm
- explorer/src/Stories/Checkbox.elm
- explorer/src/Stories/Dropdown.elm
- explorer/src/Stories/Label.elm
- explorer/src/Stories/RadioButton.elm
- explorer/src/Stories/Spinner.elm
- src/Nordea/Components/Accordion.elm
- src/Nordea/Components/Checkbox.elm
- src/Nordea/Components/Dropdown.elm
- src/Nordea/Components/Label.elm
- src/Nordea/Components/RadioButton.elm
- src/Nordea/Components/Spinner.elm
- src/Nordea/Components/StepIndicator.elm
- src/Nordea/Html.elm
- src/Nordea/Resources/Colors.elm
- src/Nordea/Resources/Icons.elm
> Partnerhub components: Label, RadioButton, Checkbox, Dropdown

- explorer/src/Explorer.elm
- explorer/src/Stories/Status.elm
- src/Nordea/Components/Status.elm
- src/Nordea/Resources/Colors.elm
Status component with custom text 🎉
> Status component

- explorer/src/Explorer.elm
- explorer/src/Stories/Text.elm
- explorer/yarn.lock
- src/Nordea/Components/Text.elm
Text component with typography variations:)
Example usage:
```elm 
Text.titleLight
|> Text.withHtmlTag Html.h2
|> Text.view [] [ text "Title light as <h2>" ]
```
> Add typography to component library

- explorer/src/Config.elm
- explorer/src/Explorer.elm
- explorer/src/Stories/ProgressBar.elm
- explorer/src/Stories/ProgressBarStepper.elm
- src/Nordea/Components/ProgressBar.elm
- src/Nordea/Components/ProgressBarStepper.elm
Added progress bar and progress bar stepper
> Add progress bar and progress bar stepper

- src/Nordea/Components/Card.elm
Fixed the Card-component. I Added flex column to the wrong component last PR 😬
> Fix: Flex column in Card component 

- src/Nordea/Components/Dropdown.elm
> Fix disabled options

- explorer/src/Config.elm
- explorer/src/Stories/FeatureBox.elm
… so its possible to click on other menu items
> Add the possibility to close the feature box 

- explorer/public/index.html
- explorer/src/Explorer.elm
- explorer/src/Stories/LottiePlayer.elm
- src/Nordea/Components/LottiePlayer.elm
- src/Nordea/Html/Attributes.elm
> Add LottiePlayer component for playing animations

- src/Nordea/Components/Checkbox.elm
- src/Nordea/Components/Dropdown.elm
- src/Nordea/Components/NumberInput.elm
- src/Nordea/Components/RadioButton.elm
- src/Nordea/Components/TextInput.elm
Update border radius, height, and hover effect of some components
> Update border radius, height, and hover effect

- explorer/src/Stories/Button.elm
- src/Nordea/Components/Button.elm
> PAR-1104: Add small card button

- explorer/src/Explorer.elm
- explorer/src/Stories/InfoPanel.elm
- src/Nordea/Components/InfoPanel.elm
- src/Nordea/Components/Text.elm
New info panel component. It lists information together with label in a grey box, separated with borders.
> Add info panel to list information

- src/Nordea/Components/Checkbox.elm
- src/Nordea/Components/RadioButton.elm
> Fix checkbox and radio button height

- src/Nordea/Components/Modal.elm
> Add media rule for mobile responsive display

- explorer/src/Stories/Dropdown.elm
- src/Nordea/Components/Dropdown.elm
Added `withPlaceholder` function to our `Dropdown` component. 
_Without the greyed out styling that the placeholder for the dropdown has in the designsystem_
> PAR-511: Added withPlaceholder function to Dropdown component

- explorer/src/Stories/Button.elm
- src/Nordea/Components/Button.elm
* Add Button variant with flat link style
> Add Button variant with flat link style

- src/Nordea/Resources/Fonts.elm
> Add sans-serif as font fallback

- src/Nordea/Components/Error.elm
Based on the locale we need to show different customer service emails
> Add correct customer service email

- src/Nordea/Components/RadioGroup.elm
Removed this in the previous PR and forgot to put it back 😅
> Add attrs to attribute list

- explorer/src/Stories/DropdownFilter.elm
- src/Nordea/Components/DropdownFilter.elm
Also fixes the following:
Now:
> Ensure that dropdown does not move other elements

- src/Nordea/Components/TextInput.elm
> Add onBlur to text input

- explorer/src/Stories/TextArea.elm
- src/Nordea/Components/TextArea.elm
Add onBlur and maxLength to TextArea
> Add onBlur and maxLength to TextArea

- src/Nordea/Components/TextInput.elm
Add onEnterPress to TextInput field
> Add onEnterPress to TextInput

- src/Nordea/Components/NumberInput.elm
> Fix formatter in NumberInput

- explorer/src/Stories/FileUpload.elm
- src/Nordea/Components/Card.elm
- src/Nordea/Components/Common.elm
- src/Nordea/Components/DropdownFilter.elm
- src/Nordea/Components/Error.elm
- src/Nordea/Components/FileUpload.elm
- src/Nordea/Components/Label.elm
- src/Nordea/Components/ProgressBarStepper.elm
- src/Nordea/Components/RadioGroup.elm
- src/Nordea/Types.elm
Some low hanging fruit. Some more controversial.
Open for discussion
> Refactor ideas

- explorer/src/Explorer.elm
- sort components (in code. Could not find a way to extract the name of stories in code)
- make categories
> sort components and make categories - #143

- src/Nordea/Components/ProgressBar.elm
No functionality change, just some cleanup
> fix type and use Nothing instead of _

- src/Nordea/Components/Button.elm
See: https://deploy-preview-195--nordea-elm-components.netlify.app/#Components/Button/Primary
https://framer.com/share/Nrdea-btn-hover-tests-1-1--ko9NxaiJTdoz6nwTIUCO/yJD_4Pn0N#yJD_4Pn0N
> Add hover transition to button

- explorer/src/Stories/Dropdown.elm
- src/Nordea/Components/Dropdown.elm
> Small dropdown

- src/Nordea/Components/Dropdown.elm
- src/Nordea/Components/NumberInput.elm
- src/Nordea/Components/TextInput.elm
- src/Nordea/Css.elm
Refactor out input sizes. 
Standard should be 3 rem and small 2.5 rem
> Standard input sizes

- src/Nordea/Components/InfoLabel.elm
> Change to smaller body text and add p-tag

- explorer/src/Stories/NumberInput.elm
- src/Nordea/Components/NumberInput.elm
> Small number input

- explorer/src/Config.elm
- explorer/src/Explorer.elm
- explorer/src/Stories/Toggle.elm
- src/Nordea/Components/Toggle.elm
> Add toggle

- explorer/src/Stories/Card.elm
- src/Nordea/Components/Card.elm
Closes #181, because that actually was an issue with the children, not the component.
Also a small refactor
> 181 - card content 🙃

- explorer/src/Explorer.elm
- explorer/src/Stories/InformationDetails.elm
- src/Nordea/Components/InformationDetails.elm
> 191 - Informationdetails

- explorer/src/Explorer.elm
- explorer/src/Stories/Colors.elm
- src/Nordea/Resources/Colors.elm
- Added primary colors to token category
> Hackathon-167: Added colors to token category

- explorer/src/Stories/Table.elm
- src/Nordea/Components/Table.elm
I created a smaller variant of the Table component to use in FinansFront and other internal applications. 
**Standard**
**Small**
> Small table variant

- explorer/src/Config.elm
- explorer/src/Stories/DropdownFilter.elm
- src/Nordea/Components/DropdownFilter.elm
- Remove unnecessary parameter
- Dont show dropdown if no search results
> PAR-1684: Improve dropdownFilter

- explorer/src/Stories/DropdownFilter.elm
- src/Nordea/Components/DropdownFilter.elm
> PAR: Add DropdownFilter with search icon

- explorer/src/Stories/Button.elm
- src/Nordea/Components/Button.elm
> PAR: Add action button

- explorer/src/Stories/Card.elm
- src/Nordea/Components/Card.elm
> PAR-894: Add footer support to Card

- explorer/src/Explorer.elm
- explorer/src/Stories/FileDownload.elm
- src/Nordea/Components/FileDownload.elm
> PAR-1743: Add document download component

- src/Nordea/Html.elm
- Added `wrappedRow` function to use in PartnerHub
> PAR-1804: Add wrappedRow function

- explorer/src/Stories/DropdownFilter.elm
- src/Nordea/Components/DropdownFilter.elm
> Add support for DropdownFilter small size

- explorer/src/Stories/Button.elm
- src/Nordea/Components/Button.elm
I renamed the constructor function as well which will not provide backwards compatibilty 🤔 Should it remain inconsistent?
> Rename small card for consistent naming

- explorer/src/Stories/Button.elm
Forgot to update the story description of SmallCard after #240
> Update story description

- src/Nordea/Components/Dropdown.elm
- src/Nordea/Components/DropdownFilter.elm
**Changes**
- There is too much space in the drop-down below the search result
- Make the “X” smaller (1rem)
- Looks like its the wrong font once you’ve selected something
❔**Questions**
- Seems a bit weird that the `Tooltip` component is used for showing search content for the `DropdownFilter`🤔 Is this something we should change?
📸**Screenshot:**
> Par 1821 small fixes to dropdown

- src/Nordea/Components/FileUpload.elm
Files that were drag n dropped were not validated for the mime type.
> PAR-1937: Bugfix: Check mimetype for drag n drop files

- explorer/src/Explorer.elm
- explorer/src/Stories/Tabs.elm
- src/Nordea/Components/Tabs.elm
> Add tabs from PH because we need it in customer portal

- src/Nordea/Components/Dropdown.elm
> Add cursor pointer to dropdown

- src/Nordea/Components/Coachmark.elm
- src/Nordea/Components/Dropdown.elm
- src/Nordea/Components/Label.elm
- src/Nordea/Components/MultiSelectDropdown.elm
The mappings should be as follows:
* blueDeep -> PrimaryColor
* blueNordea -> PrimaryColorLight
* blueMedium -> SecondaryColor
* blueHaas -> SecondaryColor
* cloudBlue -> SecondaryColor
> PAR-2241: Fix theme colors

- src/Nordea/Components/Dropdown.elm
Changed the chevron icon in simple dropdown to be smaller.
> PAR-2452: Dropdown chevron icon size change

- src/Nordea/Components/Dropdown.elm
- src/Nordea/Resources/Icons.elm
Added bolded chevron icon that is used in simple dropdowns.
> PAR-2452: Added bolded chevron icon

- src/Nordea/Components/Dropdown.elm
TextOverFlow to simple dropdown.
> PAR-2452: TextOverFlow to simple dropdown

- explorer/src/Stories/Label.elm
- explorer/src/Stories/RadioButton.elm
- src/Nordea/Components/RadioButton.elm
Remove ListStyle radiobutton since it's no longer used.
> PAR-2524: Remove ListStyle radiobutton

- review/elm.json
- review/src/ReviewConfig.elm
- src/Nordea/Components/InfoBanner.elm
- src/Nordea/Components/NumberInput.elm
- src/Nordea/Components/TextArea.elm
- src/Nordea/Components/TextInput.elm
Add elm-review simplify and run all fixes.
Also run elm-json upgrade in /review
> add elm review simplify

- src/Nordea/Components/Label.elm
> PAR-2644: Small label adjustment

- explorer/src/Config.elm
- explorer/src/Stories/InformationDetails.elm
- src/Nordea/Components/Card.elm
- src/Nordea/Components/InformationDetails.elm
Removed line grey line from header and ability to pass onClick msg for tracking.
> PAR-2638: Small adjustment on main card component

- src/Nordea/Components/RadioButton.elm
> PAR-2645: Add box shadow on hover and focus to radiomark

- explorer/src/Stories/Status.elm
- src/Nordea/Components/Status.elm
> PAR-2139: support partially filled status labels

- explorer/src/Stories/RadioButton.elm
- src/Nordea/Components/RadioButton.elm
Add small radio buttons 
https://www.figma.com/file/d7rS5EkSr1xMLupCrf0VTh/FinansFront-Sketches?type=design&node-id=120-1784&mode=design&t=JOYtQSAuLwgLYNNA-0
> PAR-2722: Add small radio button

- explorer/src/Stories/Checkbox.elm
- src/Nordea/Components/Checkbox.elm
Small checkbox component
https://www.figma.com/file/d7rS5EkSr1xMLupCrf0VTh/FinansFront-Sketches?type=design&node-id=92-8828&mode=design&t=yCQINbtgfMOY3zJ3-0
> PAR-2721: Add small checkbox component

- explorer/src/Stories/Label.elm
- src/Nordea/Components/Label.elm
Add small version of label which could be used with the small version of other components
> PAR-2746: Add small label component

- explorer/src/Stories/RadioButton.elm
- src/Nordea/Components/RadioButton.elm
Fix small radio button height to 1.5rem
> PAR: Fix small radio button height

- explorer/src/Stories/Modal.elm
- src/Nordea/Components/Modal.elm
Small version of modal component which will be used in FF.
> Add small modal component

- README.md
- explorer/src/Explorer.elm
- explorer/src/Stories/SortableTable.elm
- src/Nordea/Components/SortableTable.elm
Since this component is shared between two teams. It makes sense to add it to component library.
Will add example with sortable columns later.
> Add table that is shared between PH and KP

- explorer/src/Stories/SortableTable.elm
> Make table more visible

- explorer/src/Config.elm
- explorer/src/Stories/SortableTable.elm
- explorer/src/Stories/SortableTableSharedTypes.elm
- src/Nordea/Components/SortableTable.elm
Allow to style text inside table cells to make them right aligned in a backward compatible way.
> Make it possible to have right aligned column

- explorer/src/Config.elm
- explorer/src/Explorer.elm
- explorer/src/Stories/Snackbar.elm
- src/Nordea/Components/Snackbar.elm
Copied from partnerhub because we want to use it in the customer portal
> add snackbar component

- explorer/src/Config.elm
- explorer/src/Stories/DropdownFilter.elm
- src/Nordea/Components/DropdownFilter.elm
New design for dropdown filter to distinguish between when a value is selected or not.
https://www.figma.com/file/kYwX37EcYMAqXc95etHyGx/JiraHub?type=design&node-id=3136-17448&mode=design&t=FbaokVrH7yGhPycX-0
> lock dropdownfilter after value is selected

- explorer/src/Stories/DropdownFilter.elm
- src/Nordea/Components/DropdownFilter.elm
To be used in effectuate buyout form in FF
> add small variant to dropdownfilter

- src/Nordea/Components/Tooltip.elm
Exclude content from dom if visibility is hidden
> Adjust tooltip

- explorer/src/Stories/FileDownload.elm
- src/Nordea/Components/FileDownload.elm
Simply removing the requirement for a onClick msg enables support for hrefs too.
> Update "FileDownload" component to support hrefs

- explorer/src/Stories/Icons.elm
> add pdf icon to explorer

- elm.json
- explorer/elm.json
- explorer/src/Config.elm
- explorer/src/Explorer.elm
- explorer/src/Stories/DatePicker.elm
- src/Nordea/Components/DatePicker.elm
Add date picker component 
https://www.figma.com/design/tgFkTfmNZE0zwx44OeaohE/New-Design-System-anno-2023?node-id=16-16701&t=cX7W8hkrEqrIQiaj-0
> Add date picker component

- src/Nordea/Components/DatePicker.elm
- src/Nordea/Resources/Icons.elm
Improvements to month navigation
Hover:
Focus style:
> Improvements to month navigation in datepicker

- explorer/src/Stories/FileUpload.elm
- src/Nordea/Components/FileUpload.elm
> Tiny FileUpload

- explorer/src/Explorer.elm
- explorer/src/Stories/Chat.elm
- src/Nordea/Components/Chat.elm
- src/Nordea/Resources/Illustrations.elm
https://www.figma.com/design/kYwX37EcYMAqXc95etHyGx/SketchHub?node-id=4604-38875&t=zxN4BSnlqofZAuro-0
> Add chat component

- explorer/src/Stories/Chat.elm
- src/Nordea/Components/Chat.elm
Removed the TextArea and Send Button from chat component and allow to add child elements or custom content. Also, added scroll to chat history.
> Update chat component

- explorer/src/Config.elm
- explorer/src/Explorer.elm
- explorer/src/Stories/FiveStarRating.elm
- src/Nordea/Components/FiveStarRating.elm
Component for selecting a rating out of five stars. Based on  https://www.figma.com/file/d7rS5EkSr1xMLupCrf0VTh/FinansFront-Sketches?type=design&node-id=1603-235&mode=design
Usage example : https://github.com/SGFinansAS/FinansFront/pull/8539/files
[Screencast from 2024-07-12 12-46-26.webm](https://github.com/user-attachments/assets/cae2f0a2-d467-46ca-9995-8fc0a1761047)
> FiveStarRating component

- explorer/src/Stories/Badge.elm
- src/Nordea/Components/Badge.elm
> Add top placement for badge

- explorer/src/Explorer.elm
- explorer/src/Stories/Chat.elm
- explorer/src/Stories/Tag.elm
- src/Nordea/Components/Chat.elm
- src/Nordea/Components/Tag.elm
- src/Nordea/Resources/Colors.elm
Add tag component to the library.
> Add tag component

- explorer/src/Stories/Icons.elm
- Mostly done automatically, sed expressions used: 
```sed
s/ (iconsRow) *$/ \1WithDescription /g 
s/([^(]) Icons\.([[:alnum:]]+).*/\1 ( Icons.\2, "\2" )/g
```
> Add icon names to all icons

- src/Nordea/Components/DatePicker.elm
https://github.com/SGFinansAS/PartnerHub/issues/2859#issue-2594111458
> Fix cursor in datepicker

- explorer/src/Stories/Badge.elm
- src/Nordea/Components/Badge.elm
Updated Badge component to have more variations. Updated the design for Generic type
**Badge without icon**
**Badge with max char count**
**Generic**
> Update Badge component

- src/Nordea/Components/Chat.elm
- src/Nordea/Components/FileUpload.elm
The conditions were updated wrongly in this PR https://github.com/SGFinansAS/elm-components/pull/432
**src/Nordea/Components/Chat.elm**
**src/Nordea/Components/FileUpload.elm**
> Fix not empty conditions

- src/Nordea/Css.elm
Works similarly to Attribute.attrMaybe
> Add Css.propertyMaybe helper 

- explorer/src/Stories/Illustrations.elm
- src/Nordea/Resources/Illustrations.elm
> Add instructional info illustration

- src/Nordea/Components/Chat.elm
Add word break for messages in chat component
> Add word break for messages in chat component

- explorer/src/Stories/Chat.elm
- src/Nordea/Components/Chat.elm
- src/Nordea/Resources/Colors.elm
Allow adding message chip in the chat component
> Add message chip to Chat component

- explorer/src/Stories/MultiSelectDropdown.elm
- src/Nordea/Components/MultiSelectDropdown.elm
Just add the possbility of adding an error that is then forwarded to the label.
Also toggle outline color
> Add error to multiselectdropdown

- explorer/src/Stories/Chat.elm
- src/Nordea/Components/Chat.elm
Make chat component collapsible
> Make chat component collapsible

- src/Nordea/Components/MultiSelectDropdown.elm
fix search bar icon placement, and also use less hacky non-absolute placement and such
Old:
New:
> MultiSelect - fix search bar icon placement

- explorer/src/Config.elm
- src/Nordea/Components/MultiSelectDropdown.elm
Fixes for search clearing and close dropdown.
> Multiselect : fix clearable and close dropdown

- src/Nordea/Components/MultiSelectDropdown.elm
> MultiSelect. fix height

- src/Nordea/Components/MultiSelectDropdown.elm
Seemed fine in the explorer, but when used in CP, it got grey because of some stupid default user style agent............
> Fix multiselect background color

- explorer/src/Stories/Chat.elm
- src/Nordea/Components/AccordionMenu.elm
- src/Nordea/Components/Card.elm
- src/Nordea/Components/Chat.elm
- src/Nordea/Components/FileUpload.elm
Make the title of the chat card label the card itself. Hide icons.
> Chat accessibility

- explorer/src/Stories/Chat.elm
- src/Nordea/Components/Chat.elm
Support showing that a message was deleted in the chat
> Support showing that a message was deleted in the chat
