explorer/src/Stories/FlatLink.elm
src/Nordea/Components/Button.elm
src/Nordea/Components/FlatLink.elm

By using the `withButtonStyles` function for FlatLink, we can now have a-tags styled as buttons

Support for FlatLink styled as a Button

---

.gitignore
explorer/src/Stories/TextInput.elm
src/Nordea/Components/TextInput.elm

As a step closer to getting full error handling on text input I have added red border when withError is set to True.

Add error border line on text input

---

.gitignore
explorer/src/Stories/Dropdown.elm
explorer/src/Stories/NumberInput.elm
src/Nordea/Components/Dropdown.elm
src/Nordea/Components/NumberInput.elm

As a follow up on https://github.com/SGFinansAS/elm-components/pull/24 I have added withError on NumberInput and Dropdown, which will add an red border if an error exists

Error border on NumberInput and Dropdown

---

explorer/src/Stories/Checkbox.elm
explorer/src/Stories/RadioButton.elm
src/Nordea/Components/Checkbox.elm
src/Nordea/Components/RadioButton.elm

Adding error borders to radiobuttons and checkboxes. 
Later, when implementing the concept of a radio group we might add functionality to set error to a whole group.

Adding error borders to radio and checkbox

---

src/Nordea/Components/InformationBox.elm
src/Nordea/Components/StepIndicator.elm

Remove padding coming naturally from list, which will center the step indicator better

Remove unnesessary padding

---

src/Nordea/Components/StepIndicator.elm

Do some margin styling on the step indicator. 
- Margin on list styles to make the step indicator lower
- Removing margin on text which otherwise will be added automatically

Small stylingfixes step indicator

---

src/Nordea/Components/RadioButton.elm

Before adding box sizing
After adding box sizing

Add box sizing to fix radio button styling

---

src/Nordea/Components/StepIndicator.elm

Add box sizing to active elements in step indicator

---

explorer/src/Stories/Button.elm
src/Nordea/Components/Button.elm

- Adds a "card" button.
- This is very much a WIP, so I was hoping we could merge it, and extend it later. Design does not seem to have landed yet on how it will look in the end. Only that we'll have a card button component.
Example of how it will be usen in PartnerHub 👇

PAR-673: Add card button.

---

explorer/src/Explorer.elm
explorer/src/Stories/Card.elm
src/Nordea/Components/Card.elm
src/Nordea/Resources/Colors.elm

Add a card with title, separation line and content to component library. To be used with or without shadow. 
Needed to add a new color to the component library, grayCool. 
We tried not to be to strict setting width/maxwidth, because we though it that might be better to set when you are using this card.

Add card with title and new color to component library

---

src/Nordea/Components/Dropdown.elm
src/Nordea/Resources/Colors.elm
src/Nordea/Resources/Icons.elm

Replace regular chevron down with a filled chevron.

Add filled chevron for dropdown

---

explorer/src/Stories/Label.elm
explorer/src/Stories/RadioButton.elm
src/Nordea/Components/Common.elm
src/Nordea/Components/Label.elm
src/Nordea/Components/RadioButton.elm
src/Nordea/Components/RadioGroup.elm

Added new component `RadioGroup` to use for grouped radio buttons.
To avoid wrapping of all groups in `Label`s we moved `bottomInfo` and `topInfo` out of `Label` and into a new `Common.elm` .
The thought is to use `topInfo` and `bottomInfo` inside the individual components instead of wrapping the components in `Label` where they are used.
To clarify: `topInfo` and `bottomInfo` will still only be used inside the `elm-components library`

Added radio groups and moved some stuff from Label

---

src/Nordea/Components/Checkbox.elm
src/Nordea/Components/Common.elm
src/Nordea/Components/NumberInput.elm
src/Nordea/Components/TextInput.elm

Working with Thea today on some design tweaks 😊 
- Added border box to checkbox to senter check (see screenshot)
- Decreased spacing between label and input
- Use rem instead of em in text and number input
- Set same radius on input fields as dropdown

Design fixes with thea

---

explorer/src/Stories/Dropdown.elm
src/Nordea/Components/Dropdown.elm

In PartnerHub, we need a simple variant of the dropdown to put in the header.

Add simple dropdown variant

---

src/Nordea/Components/Card.elm

Change how to use attrs inside Card + small fixes
**Example reason for change:**
In PartnerHub we use conditional rendering some places to decide if we want to show the Card component or not. Using `attrs` in the root-component here would be nice instead of `attrs` being used in the child-component. Any thoughts on why this _shoulndt_ be done like this?

Change how to use attrs inside Card

---

explorer/src/Stories/Dropdown.elm
explorer/src/Stories/Label.elm
src/Nordea/Components/Dropdown.elm

Dropdown component can be initiated with only value and text using the init function as before. For Dropdown components with disabled options, initWithOptionsProperties can be used:)

Add new init function to allow disabled options without breaking backwards

---

explorer/src/UIExplorer/Styled.elm

The style tag from elm-css is added as the first child of the root component (from the Html.Styled package). When a component is the root and using the first-child css selector, the style tag from elm-css becomes the first child, which breaks the styling of the component.

Fix the use of :first-child css selector in UI Explorer

---

explorer/src/Explorer.elm
explorer/src/Stories/Table.elm
src/Nordea/Components/Table.elm
src/Nordea/Resources/Colors.elm

- Adding a first edition of a table component of type A table (See screenshot)
- This first edition will miss a lot of the features that is displayed in the screenshot, but implements the basic building structures
How it looks when showcased in the component library 👇

Add-table-component: Added basic structure for table

---

src/Nordea/Components/Button.elm

Somehow the flatlink button had a border and background when used with other applications, but Storybook Explorer didnt show it.

Fix FlatLink button

---

explorer/README.md
explorer/package.json

Netlify does not support symlinks, and therefore we have to copy fonts to `public` at build time. This PR adds a Yarn script that creates a symlink to the `fonts` directory that can be used in a development environment.

Add script to symlink fonts for dev environment

---

src/Nordea/Components/InfoPanel.elm

Let views using the InfoPanel component set width restrictions instead

Remove width restrictions on InfoPanel

---

src/Nordea/Components/NumberInput.elm

In this PR we are moving the input of the number input to the right. 
We are also removing the default arrow icon which increases and decreases the input number, because it was colliding with the right input.

Move number input to the right

---

explorer/src/Config.elm
explorer/src/Stories/DropdownFilter.elm
src/Nordea/Components/DropdownFilter.elm

- Add cross to dropdown filter, which deletes search string when clicked
- Add scroll to the list of elements for the search, rather than the search box and the list of results. This must also be fixed in leasing.
- Add cursor pointer to the icon in the search box
- Add padding to input field so it is not possible to write search string over the icon in the search box
Now:
With scroll now:
Previous:

Fix styling for dropdown filter

---

src/Nordea/Components/RadioGroup.elm

Remove default border and padding from RadioGroup

---

explorer/src/Stories/Spinner.elm
src/Nordea/Components/Spinner.elm

Added an alternative to Spinner component without defined standard width. This way we can use it places like inside buttons etc with custom widths without having to use `Css.important` to overwrite.

Add spinner with custom width

---

explorer/src/Stories/Error.elm
src/Nordea/Components/Common.elm
src/Nordea/Components/DropdownFilter.elm
src/Nordea/Components/Error.elm
src/Nordea/Components/Label.elm
src/Nordea/Components/ProgressBarStepper.elm

- In all translations there is added an english text translation
- The Error pages now have to send in their support email by default. This is because it does not make sense to relate email to language (country, yes, language, no), and also, it is very likely that we have different customer support emails for different systems 😊

[NB: Breaking changes] Allow english text translations

---

src/Nordea/Components/Label.elm

Useful when we use the `Label.withRequirednessHint`. With (pct 100) it pushes the hint to the end.
Example:

Add width to GroupLabel style

---

src/Nordea/Components/TextArea.elm

The Grammarly browser extension modifies the DOM, which crashes Elm. This PR disables the extension.

Disable grammarly browser extension

---

explorer/src/Stories/TextInput.elm
src/Nordea/Components/TextInput.elm

Add "small" version of input fields #144
The difference between 48px(3 rem) and 41px(2.5625 rem) is not that, I guess.

#144 - Small Textinput

---

src/Nordea/Components/StepIndicator.elm
src/Nordea/Resources/Icons.elm

I noticed that the ✔️ icon wasn't wrapped  `iconContainer` and didn't take attributes as parameters.
I'll also look into stories for icons

Add attributes to check icon

---

src/Nordea/Components/FlatLink.elm

The difference can't be seen on localhost, but will work in production, because of font issues

#142 Add font-weight 500 to flatlink

---

explorer/src/Stories/Card.elm
src/Nordea/Components/Card.elm
src/Nordea/Html.elm

- Adds an `infoBox` component to the `Card` component concept

PAR-Add-card-infobox: Addded infoBox component to Card component

---

src/Nordea/Components/Slider.elm

Fixes the Slider's default fieldset border styling because Storybook Explorer hides it

Fix: Slider - stupid explorer default styling

---

explorer/src/Config.elm
explorer/src/Stories/DropdownFilter.elm
explorer/src/Stories/Tooltip.elm
src/Nordea/Components/Dropdown.elm
src/Nordea/Components/DropdownFilter.elm
src/Nordea/Components/TextInput.elm
src/Nordea/Components/Tooltip.elm

* Support for generic content in the Tooltip component
* Based on https://github.com/SGFinansAS/elm-components/pull/204 and the requirements from PartnerHub
* Make DropdownFilter use the Tooltip component
* Simplify focus logic in DropdownFilter component
* Fix Tooltip fade out animation

Make tooltip overlay support generic content

---

explorer/src/Stories/MultiSelectDropdown.elm
src/Nordea/Components/MultiSelectDropdown.elm

- Removed default styling from `fieldset` and `ul` html elements. Default styling were not visible here for some reason. Could be css files added by explorer library? 
- Also prevents event from bubbling up when selecting an option in the dropdown

PAR-1878: Prevents event from selecting checkbox from bubbling up

---

src/Nordea/Components/MultiSelectDropdown.elm

Previously if the component were used on a page with gray backgroundcolor the component would inherit this color. Now it is white no matter the backgroundcolor of the parent element in the DOM

PAR: Added white backgroundcolor to component

---

src/Nordea/Components/NumberInput.elm

To disable the NumberInput component, we should use e.g. `|> NumberInput.view [ disabled True ]`
Deleted unused `withIsDisabled` to avoid confusing

Delete exposed 'withIsDisabled' in NumberInput component

---

src/Nordea/Components/MultiSelectDropdown.elm

Fixed z-index. The input field should not have z-index to 1, but the actual dropdown view 😊

PAR-2054: Edited zindex

---

src/Nordea/Components/NumberInput.elm

The formatter of NumberInput component prevents users from typing decimal because the formatter would format unfinished number typing.
e.g. when users try to type "123.45", before finish typing, the formatter would format "123." to "123". Which make it not possible to type decimal numbers.

NumberInput formatter not works for typing decimal

---

explorer/src/Stories/Table.elm
src/Nordea/Components/Table.elm

1. Adds a smaller table variant (FinansFront ❤️)
2. Exposes the internal variant type instead of creating `tbodyExtraSmall` and `theadExtraSmall` functions
3. Explorer example
4. Changes the `t(head|body)WithVariant` function API to take `Variant` first, a little bit cleaner IMO 
Should we remove the `t(head|body)Small` functions? They make writing tables a little bit terser, but I would argue that fidgeting with the `table`, `thead` and `tbody` elements in the HTML is very "low level" and will probably be abstracted away anyway by to some nice function like `myNiceTableFunc: List MyCoolDomainModelType -> Html msg`. This _will_ break backwards compatibility though so is it worth it to have a "neater" `Table` component API? 
@vetlesolgaard would appreciate you and/or your team's input on …

Extra small table variant

---

src/Nordea/Components/ProgressBar.elm

Before:
If you set progress to < 0 and > 100, you get weird (but kinda makes sense) results as shown above.
this clamps progress between 0 and 100, so this never happens.
progress < 0 and progress > 100 is of course an implementation error in the apps, but
I guess it can be nice to just fix it here also, so it looks a bit more sensible to the users
Open for suggestion/just closing

Clamp progress 0 100 to fix weird visual bugs

---

src/Nordea/Themes.elm

Fallbacks work a bit different for css variables. Need to provide a unknown variable in other to trigger a fallback, not an actual color.

PAR: Fix themes

---

explorer/src/Explorer.elm
explorer/src/Stories/SkeletonLoader.elm
src/Nordea/Components/SkeletonLoader.elm

Skeleton loader is already used in PH, so added here as a component. The component in itself is an empty div with styling, so shape and size specifications are passed as parameters. I added two examples to the UI Explorer for illustrations.
Screenshots:

Add SkeletonLoader component

---

explorer/src/Stories/Modal.elm
src/Nordea/Components/Modal.elm

At least ESign is affected. What makes this particularly bad is inability to close the dialog for example on a mobile device if close button and eXit icon are on the right.
<details><summary>Old behavior GIF</summary>
</details>
<details><summary>Fixed</summary>
</details>

Fix clipping of modal dialogs on narrow screens

---

explorer/src/Stories/InformationDetails.elm
src/Nordea/Components/AccordionMenu.elm
src/Nordea/Components/Card.elm
src/Nordea/Components/InformationDetails.elm

Implemented collapsible Card in addition to the regular one. Collapsible card component is used in InformationDetails.  'emphasisedText' fades in and out when card is collapsed/uncollapsed.

PAR-2347: Collapsible InformationDetails Card

---

explorer/src/Config.elm
explorer/src/Stories/TextInput.elm
src/Nordea/Components/TextInput.elm

Eliminates the `if-else` in the `view`. e.g.
```
if Maybe.isJust config.onClearInput then
...
else if config.hasSearchIcon then
...
else
...
```
I think one could not have both cross and search icon at the same time previously due to that. Fixes to one single view.
Uses the webkit property for cross icon. This way, we can use the same onInput msg on clear. not available in firefox.
Screenshots from chrome
This one is a bit problematic. Do we like the placement of the cross, should we bring it left always or when there is currency or leave it like this?

PAR-2624: use the onInput msg for onClear in text inputs

---

explorer/src/Stories/NumberInput.elm
explorer/src/Stories/TextInput.elm
src/Nordea/Components/NumberInput.elm
src/Nordea/Components/TextInput.elm

Add small size component so we can use in FF
https://www.figma.com/file/d7rS5EkSr1xMLupCrf0VTh/FinansFront-Sketches?type=design&node-id=90-5800&mode=design&t=pPkrv2KY7Nl6FUnk-0

PAR-2720: Add small size for text and number input

---

explorer/src/Stories/Dropdown.elm
src/Nordea/Components/Dropdown.elm
src/Nordea/Resources/Icons.elm

Added a small size version of the dropdown component, to align with design decisions made for FinansFront.
Screenshot:

Add small size dropdown component

---

explorer/src/Stories/TextInput.elm
src/Nordea/Components/TextInput.elm

Fix padding on Standard input field 
Small with search icon
Small with currency
Small with cancel icon

PAR-2747: Adjustments to small text input to use with icons

---

explorer/src/Stories/Tooltip.elm
src/Nordea/Components/Coachmark.elm
src/Nordea/Components/Tooltip.elm

The design library has more placements than just the arrow being on the center.
https://www.figma.com/file/tgFkTfmNZE0zwx44OeaohE/New-Design-System-anno-2023?type=design&node-id=8-1997&mode=design&t=2juhpiu62fIbnojD-0
Introduce 3 variants, `NearCorner, NearOtherCorner, Center` for arrow placement.

PAR-2742: new arrow placements for tooltip

---

src/Nordea/Components/DropdownFilter.elm
src/Nordea/Components/Tooltip.elm

`min-width` was removed some time ago from tooltip and later it caused issues for `DropdownFilter`, and as part of fix it was added again here https://github.com/SGFinansAS/elm-components/pull/345
But the fix there also caused an issue in tooltip like below
The tooltip lost its position at the center, and `min-width` caused the tooltip to cover a very large area (as big as the element that is being tooltipped). This is bad because you cannot click anything because of z-index.
Now with this fix, both dropdown and tooltip should work as intended.

fix tooltip width and z-index issue

---

explorer/src/Stories/Card.elm
explorer/src/Stories/Checkbox.elm
explorer/src/Stories/Coachmark.elm
explorer/src/Stories/Colors.elm
explorer/src/Stories/FilterChip.elm
explorer/src/Stories/Icons.elm
explorer/src/Stories/Label.elm
explorer/src/Stories/RadioButton.elm
src/Nordea/Components/Checkbox.elm
src/Nordea/Components/Coachmark.elm
src/Nordea/Components/FilterChip.elm
src/Nordea/Components/MultiSelectDropdown.elm
src/Nordea/Components/RadioButton.elm
src/Nordea/Components/SortableTable.elm
src/Nordea/Css.elm

Annoying and error prone to write Css.property "gap" "1rem" instead of `gap (rem 1)` like you would for height,length and such. 
This fixes that :))
Also easier to read and more in line with most other props
Copied the type from the Css-library, so it works with rem/px/pct and such
* gap (rem 1)
* gap (px 1)

Add gap css function

---

src/Nordea/Css.elm

Add helper functions for properties that are related to CSS Grids.
Elm-css is a bit outdated and does not support newer CSS syntax. This is a continuation of @morteako 's idea of adding the missing functions to the component library (`gap` and `gap2` in his case).
I haven't done the effort of typing these functions in a sophisticated way, so most just accept a single _string_ parameter. Adding better types would be a greater effort since the Grid spec introduces a bunch of new units that are also not present in elm-css. Anyway, I think it adds some value to be able to type:
```elm
css
[ displayGrid
, gridTemplateColumns "repeat(4, 1fr)"
]
```
Instead of:
```elm
css
[ Css.property "display" "grid"
, Css.property "grid-template-columns" "repeat(4, 1fr)"
]
```
Added some links to MDN as well …

Add helper functions for CSS properties related to grids

---

src/Nordea/Components/Modal.elm

Rename `msg` to `onClickClose`, as is the naming in `init onClickClose variant = ....`

Modal : Fix inconsistent and unclear naming

---

explorer/src/Stories/DropdownFilter.elm
src/Nordea/Components/DropdownFilter.elm

Adds the option to add a placeholder (`placeholder : Maybe String` and `withPlaceholder`) 
Adds `withHasError` function where you can specifically set the error, instead of it only coming from 0 matches.
The model already has `hasError : Bool` , but it is defaulted to False and previously not possible to change.

DropdownFilter: Add Placeholder and withHasError-function

---

src/Nordea/Components/DatePicker.elm
src/Nordea/Resources/Icons.elm

Removed chevronRightBordered icon since using svg with mask was not ideal. We cannot reuse the icon in the same page since the mask id needs to be unique. So update datepicker to use two icons one on top of other during focus.

Fix datepicker month navigation

---

src/Nordea/Components/DatePicker.elm

Clicking anywhere inside the datepicker closes it. So, added prevent default method to avoid this.

Prevent default when clicking inside datepicker

---

src/Nordea/Components/TextInput.elm

- This allows us to do things like direct focus on the input element (using Browser.Dom).

Add withId so that we can give an Dom id to the input element

---

src/Nordea/Components/Modal.elm
src/Nordea/Html/Events.elm

- It's useful when building accessible components.
- Needed to e.g. close dropdown on ESC.
Also see discussion at the end of https://github.com/SGFinansAS/elm-components/pull/383

Add onEscPress to Html.Events

---

src/Nordea/Html/Events.elm

Bug fix where the `onEnterPress` event listened to Spacebar instead of Enter-key.

Fix - onEnterPress keycode 

---

explorer/src/Stories/DropdownFilter.elm
src/Nordea/Components/DropdownFilter.elm

Allow disabling the DropdownFilter.
Use case in FF: 
[Screen recording](https://github.com/user-attachments/assets/eed325e5-b953-4851-9d43-e6315b587aa0)

DropdownFilter.withDisabled

---

elm.json
explorer/elm.json
explorer/src/Config.elm
explorer/src/Stories/FileUpload.elm
src/Nordea/Components/FileUpload.elm
src/Nordea/Html.elm

- Adds a unified FileUpload view for single file uploads (with RemoteData for upload state) .
- This also fixes a bug where Decode errors out when added files were not on the accepted list - allowing the drop event to bubble to the top, showing the file contents in the browser.
-  Still not 100% compatible with CP design docs; need to discuss cross-team that all have the same design req.
Breaks API: onFilesSelected handler gives a List that can be empty.

Add a unified FileUpload view for single file uploads

---

src/Nordea/Components/Label.elm

- Small screens that need to squeeze the labels will otherwise have the hint too close to the label.
Before:
After:

Add some spacing to the label requireness hint

---

explorer/src/Stories/Chat.elm
src/Nordea/Components/Chat.elm

In some cases we might not want to show the sender name and only show the message channel. So changed sender to option type.

Make chat sender optional

---

explorer/src/Config.elm
explorer/src/Explorer.elm
explorer/src/Stories/AccordionTable.elm
src/Nordea/Components/AccordionTableHeader.elm
src/Nordea/Components/AccordionTableRow.elm

I've added two new components from FinansFront:
- AccordionTableHeader
- AccordionTableRow
When these are used inside a CSS Grid, you can compose this sort of «AccordionTable». Note that the column headers are not part of the library.
Here's the smaller variant for FinansFront:
This layout style is used all over the place in new sketches, including the new Supplier Invoice Page, Change of Party applications and the new ESign page in FinansFront.
The AccordionTable is a mix of two features; the CSS Grid specification and the details/summary HTML elements.
The details and summary are native HTML elements that make the accordions expand and collapse when clicked. They are accessible and works without Javascript.
Each row in the table are made out of these elements. So how do we align the …

Accordion table components

---

explorer/src/Stories/Status.elm
src/Nordea/Components/Status.elm

Add a small variant of the Status component for FinansFront. Also, add some extra _horizontal_ padding on the larger variant (from `0.5` to `0.75rem`), as discussed with Line.

Add smaller status components

---

explorer/src/Stories/Chat.elm
src/Nordea/Components/Chat.elm

Handle text overflow when the chat `sentFrom`  value is too long.

Handle text overflow for chat 

---

src/Nordea/Components/Chat.elm

Chat history max height is too long so reduced it. Also made the scroll bar width to be thin.

Change max height of chat history

---

src/Nordea/Components/AccordionTableRow.elm

This is a workaround for a bug in Chrome that messes up the Grid layout when using the HTML details element together with the `display: contents` rule. The bug is currently apparent on the Supplier Invoice and Change of Party pages in FinansFront.
Fixed as described on the Chrome bug tracking site: https://issues.chromium.org/issues/40069963
Before:
After:

Workaround for Chrome bug in details element

---

explorer/src/Stories/Card.elm
explorer/src/Stories/InformationDetails.elm
src/Nordea/Components/Card.elm
src/Nordea/Components/InformationDetails.elm

Make emphasised text optional in collapsible card.

Make emphasised text optional in card

---

explorer/src/Config.elm
explorer/src/Stories/Label.elm
src/Nordea/Components/Label.elm
src/Nordea/Css.elm

Currently Label doesn't reserve space for the error message resulting in a noticable UI jerk when the error message takes up new space. Fix this by reserving space for the error message using visibility: hidden, also only do this if withError is used to avoid noticeable changes for other users.
Also 
- Enhance stories so that the problem can be reproduced in-tree.
- Add a cssIf helper, couldn't find anything matching this; holler if you know an existing implementation!
https://github.com/user-attachments/assets/bd27f029-4018-415c-b3c2-3e6817565fb4

Avoid jerking the UI when showing error message

---

src/Nordea/Components/FlatLink.elm

Flatlink with `Mini` variant should use styles of button size `small`.

Mini flatlink should use small button size

---

src/Nordea/Components/Label.elm

Introduce a `Label.withNoReservedErrorSpace` for opting out of the current behaviour that reserves space below the Label component if using `Label.withErrorMessage Nothing`
---
When using `Label.withErrorMessage`, the Label component reserves space for the error message, even if the provided error message is `Nothing`. This makes it difficult to control spacing between components in a form.
I'm not sure if this behaviour is a feature or a bug. This PR proposes a bugfix.
Works as expected.
```elm
Label.init "No error message" Label.InputLabel
```
Works as expected.
```elm
Label.init "With error message" Label.InputLabel
|> Label.withErrorMessage (Just "Message")
```
Notice the extra space between the second and third field.
```elm
Label.init "With empty error message" Label.InputLabel
|> …
```

Introduce helper to opt out of reserving space for errors on labels

---

explorer/src/Stories/NumberInput.elm
src/Nordea/Components/NumberInput.elm

Added options for
- Aligning the text to left
- Using "KR" or "%" suffixes.

Add builder methods to NumberInput for alignment and suffix

---

src/Nordea/Components/Chat.elm

Using lighter blue shade (cloudBlue) now. Also, changed to use brighter shade for users message and lighter one for incoming messages. Since it is the standard used in other messaging services 
https://www.figma.com/design/wErdj7sE82qBlsDe05HA4s/SketchHub?node-id=8792-35801&t=99P6tkDFTewsItD1-0

Improve blue contrast in chat component

---

src/Nordea/Components/Label.elm

Reverts SGFinansAS/elm-components#458
Reverting this since it other than input fields combined with group label looked off.

Revert "Group label bottom margin fix"

---

explorer/src/Stories/MultiSelectDropdown.elm
src/Nordea/Components/MultiSelectDropdown.elm

Adds groups to multiselectdropdown. See design on left.
I have not changed the actual design and spacing of the select items, so it is not 100% as the design.
I have kept the current withOptions-functions, so it should be non-breaking

Add groups to multiselect

---

elm.json
explorer/elm.json
explorer/src/Config.elm
explorer/src/Explorer.elm
explorer/src/Stories/MultiSelectDropdown.elm
src/Nordea/Components/MultiSelectDropdown.elm
src/Nordea/Html/Events.elm

Add the showing of the selected items, for the multiselect with filter. 
(Not implemented for the non search-filter version. that can be added later)
To fix input focus when clicking the non-input-row, i need to use Browser.Dom.focus from elm/browser.

MultiCompanySelector - add selected before input

---

explorer/src/Stories/TextArea.elm
src/Nordea/Components/TextArea.elm

Add TextArea.withSmallSize. Took some inspiration from TextInput.withSmallSize
[small-textarea.webm](https://github.com/user-attachments/assets/44413573-4131-4131-af6f-0f451108598c)

TextArea.withSmallSize

---

src/Nordea/Components/Chat.elm

Allow html title in chat component instead of just the text. Also removed Beta tag from the component since it is not used anywhere and it can be added as part of title if needed.

Allow html title in chat component

---

src/Nordea/Components/Label.elm

The bool currently makes it hard to make a consistent layout when mixing form controls with and without errors.

Remove 'withError' on label
